services:
  todo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src
  todo-dev:
    build: 
      context: .
      target: development
    ports:
      - '3003:3003'
    environment:
      - PORT=3003
    volumes:
      - C:\Users\camic\Desktop\Practica\todonestjs\todolist\src:/usr/src/app/src
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=todolist
      - MYSQL_TCP_PORT=3306
  